apiVersion: v1
kind: Deployment
metadata:
  labels:
    name: springboot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: dockerravi79/spring-boot-maven-example-helloworld
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: springboot
